RunConfig:
  Name: OPERA-TROPO-PGE-SAMPLE-CONFIG
  Groups:
    PGE:
      PGENameGroup:
        PGEName: TROPO_PGE
      InputFilesGroup:
        InputFilePaths:
        - /opt/airflow/config/tropo-objects/example-tropo-2.rtf
      DynamicAncillaryFilesGroup:
        AncillaryFileMap: {}
      ProductPathGroup:
        OutputProductPath: /home/ops/output_dir
        ScratchPath: /home/ops/scratch_dir
      PrimaryExecutable:
        ProductIdentifier: TROPO
        ProductVersion: '0.3'
        ProgramPath: opera_tropo
        ProgramOptions:
        - run
        ErrorCodeBase: 800000
        SchemaPath: /home/ops/opera/pge/tropo/schema/tropo_sas_schema.yaml
        AlgorithmParametersSchemaPath: ''
        IsoMeasuredParameterDescriptions: /home/ops/opera/pge/tropo/templates/tropo_measured_parameters.yaml
        IsoTemplatePath: /home/ops/opera/pge/tropo/templates/OPERA_ISO_metadata_L4_TROPO_template.xml.jinja2
      QAExecutable:
        Enabled: false
        ProgramPath: null
        ProgramOptions: []
      DebugLevelGroup:
        DebugSwitch: false
        ExecuteViaShell: true
    SAS:
      input_file:
        input_file_path: /opt/airflow/config/tropo-objects/example-tropo-2.rtf
      primary_executable:
        product_type: OPERA_TROPO
      product_path_group:
        product_path: /home/ops/output_dir
        scratch_path: /home/ops/scratch_dir
        sas_output_path: /home/ops/output_dir
        product_version: '0.3'
      worker_settings:
        n_workers: 8
        threads_per_worker: 2
        max_memory: 8GB
        dask_temp_dir: tmp
        block_shape:
        - 128
        - 128
      output_options:
        output_heights:
        - -500.0
        - -300.0
        - -200.0
        - -100.0
        - -50.0
        - -20.0
        - -10.0
        - 0.0
        - 10.0
        - 30.96
        - 53.92
        - 79.04
        - 106.54
        - 136.62
        - 169.51
        - 205.44
        - 244.69
        - 287.52
        - 334.24
        - 385.16
        - 440.61
        - 500.95
        - 566.54
        - 637.76
        - 715.02
        - 798.72
        - 889.29
        - 987.15
        - 1092.73
        - 1206.44
        - 1328.7
        - 1459.91
        - 1600.44
        - 1750.63
        - 1910.76
        - 2081.09
        - 2261.8
        - 2452.99
        - 2654.69
        - 2866.83
        - 3089.25
        - 3321.67
        - 3563.69
        - 3814.82
        - 4074.41
        - 4341.73
        - 4615.92
        - 4896.02
        - 5180.98
        - 5469.3
        - 5759.3
        - 6049.89
        - 6340.68
        - 6631.66
        - 6922.8
        - 7214.09
        - 7505.51
        - 7797.04
        - 8088.67
        - 8380.36
        - 8672.11
        - 8963.9
        - 9255.7
        - 9547.49
        - 9839.26
        - 10130.98
        - 10422.64
        - 10714.22
        - 11005.69
        - 11297.93
        - 11592.86
        - 11890.24
        - 12190.1
        - 12492.44
        - 12797.3
        - 13104.7
        - 13414.65
        - 13727.18
        - 14042.3
        - 14360.05
        - 14680.44
        - 15003.5
        - 15329.24
        - 15657.7
        - 15988.88
        - 16322.83
        - 16659.55
        - 16999.08
        - 17341.62
        - 17687.77
        - 18038.35
        - 18394.25
        - 18756.34
        - 19125.61
        - 19503.09
        - 19889.88
        - 20286.66
        - 20694.9
        - 21114.77
        - 21546.62
        - 21990.82
        - 22447.75
        - 22917.85
        - 23401.71
        - 23900.02
        - 24413.5
        - 24942.93
        - 25489.15
        - 26053.04
        - 26635.56
        - 27237.73
        - 27860.64
        - 28505.47
        - 29173.5
        - 29866.09
        - 30584.71
        - 31330.96
        - 32106.57
        - 32915.27
        - 33763.05
        - 34652.52
        - 35586.89
        - 36569.72
        - 37604.95
        - 38696.94
        - 39850.56
        - 41071.2
        - 42364.93
        - 43738.55
        - 45199.69
        - 46756.98
        - 48413.94
        - 50159.36
        - 51996.21
        - 53905.62
        - 55882.68
        - 57930.78
        - 60053.46
        - 62254.39
        - 64537.43
        - 66906.53
        - 69365.77
        - 71918.79
        - 74584.91
        - 80301.65
        max_height: 81000
        chunk_size:
        - 1
        - 64
        - 64
        - 64
        compression_kwargs:
          zlib: true
          complevel: 5
          shuffle: true
      log_file: output_dir/sas_logfile.log
